### ISSUE TITLE
82mm shells fly so slow

### ISSUE THREAD

**Issue by Crutchmaster** [NoImageAvailable/CombatRealism#21]
82mm shells fly so slow. Changing <projectile><speed> in Pprojectile_Shells.xml has no effect.

**Comment by Krutchen** [comment]
I think this is actually because of how shell speed is calculated. I was playing around with CR the other day and made a man portable mortar with a low time to target. it appears as though shell speed is instead time to hit or something similar, with 100 being pretty slow, and things around 30-40 being more reasonable. Anything under that, though, and rimworld would just delete the shell before it had a chance to move, and also with those speeds there appears to be a hardcapped max range, targetting outside of said range would cause an out of bounds error.

This might be a vanilla obstacle, but i'll check out what's going on. This might be a problem in how projectiles are simulated in Combat Realism but I've got to read into this a bit

**Comment by Krutchen** [comment]
Upon looking into the defs further, 41 seems to be the default mortar speed. You could go into CombatRealism-1.6.5\Defs\ThingDefs_Ammo\Projectiles_Shells.xml and change all instances of <speed>100</speed> to <speed>41</speed> and see if that helps much?

**Comment by Crutchmaster** [comment]
I change speed for all 82mm shells to 20, 40, 300 and 500. No effect. Also one time, after destroying enemy mortar, he drops 5-6 weapons 82mm mortars.

**Comment by Crutchmaster** [comment]
I get next gameplay problem: when sieged I can easy dodge flying enemy shells. Workaround: transparent projectile.

**Comment by NoImageAvailable** [comment]
1) This repo isn't actively maintained anymore, you should make issue reports and pull requests on skullywag's forked repo. The only reason I saw this at all is because I forgot to turn of email notifications.
2) The ingame speed of projectiles is determined by the steepness of the arc they travel on. Mortars fire on a high arc between 45-90°, meaning the faster the shell and the closer the target the steeper the arc will be, resulting in longer travel times. Ingame the projectile appears slower when it is infact travelling vertically.

Furthermore, mortar shells use CompCharges to dynamically determine projectile speed according to target distance. This is to solve the issue of lower speeds giving too little range (if a projectile can't hit the target with a 45° angle of aim it will error out, ask Alistaire if you want the specifics, he did most of the ballistic calculations for the aiming system) and higher speeds giving too long travel times at shorter ranges.
